config/routes.rb
Rails.application.routes.draw do

	resources :puppies
		#    puppies GET    /puppies(.:format)          puppies#index
		#            POST   /puppies(.:format)          puppies#create
		#  new_puppy GET    /puppies/new(.:format)      puppies#new
		# edit_puppy GET    /puppies/:id/edit(.:format) puppies#edit

		#      puppy GET    /puppies/:id(.:format)      puppies#show
		#            PATCH  /puppies/:id(.:format)      puppies#update
		#            PUT    /puppies/:id(.:format)      puppies#update
		#            DELETE /puppies/:id(.:format)      puppies#destroy
	root 'puppies#index'
end

app/models/puppy.rb
class Puppy < ActiveRecord::Base
	validates :name, :age, :breed, :image, :bio, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/puppies_controller.rb
class PuppiesController < ApplicationController
  
  def index
  	@puppies = Puppy.all
  end

  def new
  	@puppy = Puppy.new
  end

  def create
   	@puppy = Puppy.new(puppy_params)
   	if @puppy.save
   		redirect_to puppies_path, flash: {success: "Puppy created!"}
   	else
   		render :new
   	end	
  end

  def show
  	find_puppy
  end

  def edit
  	find_puppy
  end

  def update
  	find_puppy.update(puppy_params)
		if find_puppy.save
			redirect_to puppy_path(find_puppy), notice: "Puppy updated"
		else
			render :edit
		end		
  end

  def destroy
  	find_puppy.destroy
  	redirect_to puppies_path, alert: "Puppy removed"
  end

  private 
  	def puppy_params	
  		params.require(:puppy).permit(:name, :age, :breed, :image, :bio)
  	end
  	def find_puppy
  		@puppy = Puppy.find_by_id params[:id]
  		@puppy
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PuppyRescue</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/puppies/_form.html.erb
<% if @puppy.errors.any? %>
  <% @puppy.errors.full_messages.each do |error| %>
    <p style="color:red;">
      <%= error %>
    </p>
  <% end %>
<% end %>
<div class="form-group">
<%= form_for @puppy do |pup|%>
  <div>
    <%= pup.label :name%>
    <%= pup.text_field :name, autofocus: true %>
  </div>
  <div>
    <%= pup.label :breed%>
    <%= pup.text_field :breed%>
  </div>
    <div>
    <%= pup.label :age%>
    <%= pup.text_field :age%>
  </div>
  <div>
    <%= pup.label :bio%>
    <%= pup.text_field :bio%>
  </div>
  <div>
    <%= pup.label :image%>
    <%= pup.text_field :image%>
  </div>
  <div>
    <%= pup.submit "save puppy" %>
  </div>
<% end %>
</div>

<% flash.each do |key, value| %>
  <% if key == "notice" %>
    <%= content_tag :div, value, class: "text-center alert alert-warning" %>
  <% elsif key == "alert" %>
    <%= content_tag :div, value, class: "text-center alert alert-danger" %>
  <% else %>
    <%= content_tag :div, value, class: "text-center alert alert-success" %>
  <% end %>
<% end %>

app/views/puppies/edit.html.erb
<h3>Change a puppy</h3>
<%= link_to "Back to puppies", puppies_path %>

<%= render 'form' %>

app/views/puppies/index.html.erb
<h3>Adopt a' puppy</h3>

<%= link_to "Add new Puppy", new_puppy_path %>

<% @puppies.each do |puppy| %>
	<table class="table table-hover">
		<tr>
			<td><img height='100' width="100" src="<%= puppy.image %>" alt=""></td>
			<td>Name:<br><%= puppy.name %></td>
			<td>Age:<%= puppy.age %></td>
			<td>Breed:<br><%= puppy.breed %></td>
			<td>Bio:<br><%= puppy.bio %></td>
			<td><%= link_to "Edit", edit_puppy_path(puppy) %></td>
		</tr>	
	</table>
	
	
<% end %>

app/views/puppies/new.html.erb
<h3>Add a new puppy</h3>
<%= link_to "Back to puppies", puppies_path %>

<%= render "form" %>

app/views/puppies/show.html.erb
<div class="one_puppy">
	<h1>Name:<%= @puppy.name %></h1>
	<p>Age:<%= @puppy.age %></p>
	<p>Breed:<%= @puppy.breed %></p>
	<p>Bio:<%= @puppy.bio %></p>
	<p><img height='100' src="<%= @puppy.image %>" alt=""></p>
	<%= link_to "Delete puppy", @puppy, method: :delete %>
</div>

<%= link_to "Back to index", puppies_path %>